### ISSUE TITLE
SQLAlchemy NoForeignKeysError on new library/add books

### ISSUE THREAD

**Issue by ghost** [grapesmoker/pdf-library#1]
I downloaded the relevant packages and ran main.py, GUI opened successfully. When I try to create a new library and Choose a root, I get this error.

(Fixing this isn't really urgent, just thought you should know)

```
(venv)~/code/pdf-library λ python2 main.py                      
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]
Traceback (most recent call last):
  File "/home/me/code/pdf-library/main_window.py", line 83, in create_new_library
    self.build_lib_from_root()
  File "/home/me/code/pdf-library/main_window.py", line 137, in build_lib_from_root
    self.import_pdf_file(full_path)
  File "/home/me/code/pdf-library/main_window.py", line 158, in import_pdf_file
    new_document = models.Document(name=title, path=full_path)
  File "<string>", line 2, in __init__
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/instrumentation.py", line 347, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 754, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/instrumentation.py", line 177, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2872, in _event_on_first_init
    configure_mappers()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2768, in configure_mappers
    mapper._post_configure_properties()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1708, in _post_configure_properties
    prop.init()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/interfaces.py", line 183, in init
    self.do_init()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1629, in do_init
    self._setup_join_conditions()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1704, in _setup_join_conditions
    can_be_synced_fn=self._columns_are_mapped
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1972, in __init__
    self._determine_joins()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 2067, in _determine_joins
    "expressions." % (self.prop, self.secondary))
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Journal.documents - there are no foreign keys linking these tables via secondary table 'document_publishers'.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify 'primaryjoin' and 'secondaryjoin' expressions.
[2]    2200 abort (core dumped)  python2 main.py
```

**Comment by grapesmoker** [comment]
Yeah, I made a typo in specifying one of the join relationships because I just cut and pasted. It should be fixed now.
